name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Generate release notes and bump version
        id: release
        run: |
          pnpm run release
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build for Chrome
        run: pnpm run build:chrome

      - name: Build for Firefox
        run: pnpm run build:firefox

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.release.outputs.new_version }}
          release_name: Release ${{ steps.release.outputs.new_version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload Chrome build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/chrome.zip
          asset_name: chrome.zip
          asset_content_type: application/zip

      - name: Upload Firefox build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/firefox.zip
          asset_name: firefox.zip
          asset_content_type: application/zip

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --follow-tags origin main
