name: Build and Release for Chrome and Firefox

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate release notes and bump version
        id: package-version
        run: |
          pnpm run release
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Push changes
        run: |
          git push --follow-tags origin main

      - name: Check for existing tag
        id: check_tag
        run: |
          if git ls-remote --exit-code --tags origin refs/tags/v${{ steps.package-version.outputs.new_version }} >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check_tag.outputs.tag_exists == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.new_version }}
          release_name: Release ${{ steps.package-version.outputs.new_version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Get Release Upload URL
        id: get_upload_url
        run: |
          if [[ "${{ steps.check_tag.outputs.tag_exists }}" == "true" ]]; then
            upload_url=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.package-version.outputs.new_version }}" \
              | jq -r .upload_url)
          else
            upload_url="${{ steps.create_release.outputs.upload_url }}"
          fi
          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT

      - name: Build for Chrome
        run: pnpm run build:chrome

      - name: Archive Chrome build files
        run: cd dist/chrome && zip -r -FS ../../build-chrome.zip . --exclude '*.git*'

      - name: Build for Firefox
        run: pnpm run build:firefox

      - name: Archive Firefox build files
        run: cd dist/firefox && zip -r -FS ../../build-firefox.zip . --exclude '*.git*'

      - name: Upload Chrome build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: ./build-chrome.zip
          asset_name: build-chrome.zip
          asset_content_type: application/zip

      - name: Upload Firefox build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: ./build-firefox.zip
          asset_name: build-firefox.zip
          asset_content_type: application/zip
